### ISSUE TITLE
OLED duration time

### ISSUE THREAD

**Issue by wok1909** [pedker/OLED-BongoCat-Revision#2]
Thank you for your wonderful program!

I just have one problem with OLED duration time.

My OLED screen turns off when I don't type about a minute.

Is there any already programmed way to customize the OLED duration time?

**Comment by pedker** [comment]
This is baked into the core firmware for the Satisfaction75, its purpose is to protect the components; OLED screens can burn in after extended use, especially uninterrupted use

The value you're looking for is `oled_sleep_timer`, defined in `satisfaction75.h` and used in `satisfaction_oled.c`
